- name: 스왑(Swap) 비활성화
  shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab
  args:
    removes: /swap.img
  ignore_errors: true

- name: K3s 설치 스크립트 실행 (Flannel/Traefik 비활성화)
  shell: |
    set -o pipefail
    curl -sfL https://get.k3s.io | \
    INSTALL_K3S_VERSION="{{ k3s_version }}" \
    INSTALL_K3S_EXEC="server --disable flannel --disable traefik --disable servicelb --write-kubeconfig-mode 644 --node-name {{ ansible_facts['hostname'] }}" \
    sh -
  args:
    executable: /bin/bash
    creates: /usr/local/bin/k3s

- name: K3s 서비스 활성화, 시작
  service:
    name: k3s
    state: started
    enabled: yes

- name: .kube 디렉토리 생성, 권한 설정
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: K3s kubeconfig 유저 홈으로 복사
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: '0600'
  become: true